-- MySQL Script generated by MySQL Workbench
-- Tue Feb 13 18:03:56 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecommerceapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerceapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerceapp` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ecommerceapp` ;

-- -----------------------------------------------------
-- Table `ecommerceapp`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerceapp`.`user` (
  `user_id`  BIGINT NOT NULL,
  `account_non_expired` TINYINT(1) NOT NULL,
  `account_non_locked` TINYINT(1) NOT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `credentials_non_expired` TINYINT(1) NOT NULL,
  `is_enabled` TINYINT(1) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `phone_number` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerceapp`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerceapp`.`product` (
  `product_id` BIGINT NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`),
  CONSTRAINT `FK979liw4xk18ncpl87u4tygx2u`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommerceapp`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerceapp`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerceapp`.`cart` (
  `quantity` INT  NOT NULL,
  `product_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`product_id`, `user_id`),
  CONSTRAINT `FK3d704slv66tw6x5hmbm6p2x3u`
    FOREIGN KEY (`product_id`)
    REFERENCES `ecommerceapp`.`product` (`product_id`),
  CONSTRAINT `FKl70asp4l4w0jmbm1tqyofho4o`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommerceapp`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerceapp`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerceapp`.`category` (
  `category_id` BIGINT NOT NULL,
  `item_count` INT  NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerceapp`.`category_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerceapp`.`category_product` (
  `product_id` BIGINT NOT NULL,
  `category_id` BIGINT NOT NULL,
  CONSTRAINT `FKfr6rjc04htbtc3xas2b9xmq7r`
    FOREIGN KEY (`category_id`)
    REFERENCES `ecommerceapp`.`category` (`category_id`),
  CONSTRAINT `FKssroqj2vyiaujfleklq1ifigj`
    FOREIGN KEY (`product_id`)
    REFERENCES `ecommerceapp`.`product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerceapp`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerceapp`.`comment` (
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `product_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`product_id`, `user_id`),
  CONSTRAINT `FK8kcum44fvpupyw6f5baccx25c`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommerceapp`.`user` (`user_id`),
  CONSTRAINT `FKm1rmnfcvq5mk26li4lit88pc5`
    FOREIGN KEY (`product_id`)
    REFERENCES `ecommerceapp`.`product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerceapp`.`favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerceapp`.`favorites` (
  `user_id` BIGINT NOT NULL,
  `product_id` BIGINT NOT NULL,
  CONSTRAINT `FK1uphh0glinnprjknyl68k1hw1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommerceapp`.`user` (`user_id`),
  CONSTRAINT `FKs08qf83fj01k3epnxh9n71v1s`
    FOREIGN KEY (`product_id`)
    REFERENCES `ecommerceapp`.`product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerceapp`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerceapp`.`notification` (
  `notification_id` BIGINT NOT NULL,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `readed` TINYINT(1) NOT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`notification_id`),
  CONSTRAINT `FKb0yvoep4h4k92ipon31wmdf7e`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommerceapp`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerceapp`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerceapp`.`orders` (
  `orders_id` BIGINT NOT NULL,
  `orders_date` DATETIME NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `total_price` DOUBLE NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`orders_id`),
  CONSTRAINT `FKel9kyl84ego2otj2accfd8mr7`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommerceapp`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerceapp`.`shipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerceapp`.`shipment` (
  `shipment_id` BIGINT NOT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `last_update` DATETIME NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`shipment_id`),
  CONSTRAINT `FKsh7hhx6dbueu6ilnf92s9jub9`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommerceapp`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerceapp`.`orders_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerceapp`.`orders_product` (
  `quantity` INT NOT NULL,
  `orders_id` BIGINT NOT NULL,
  `product_id` BIGINT NOT NULL,
  `shipment_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`orders_id`, `product_id`),
  CONSTRAINT `FK7h8a805aormf2mxryf70m1n7a`
    FOREIGN KEY (`orders_id`)
    REFERENCES `ecommerceapp`.`orders` (`orders_id`),
  CONSTRAINT `FKgp7ssuxotl2qdbdokacks4isq`
    FOREIGN KEY (`shipment_id`)
    REFERENCES `ecommerceapp`.`shipment` (`shipment_id`),
  CONSTRAINT `FKhqvk1lcdpap9qym2o94b45mcs`
    FOREIGN KEY (`product_id`)
    REFERENCES `ecommerceapp`.`product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerceapp`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerceapp`.`role` (
  `role_id` BIGINT NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerceapp`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerceapp`.`user_role` (
  `user_id` BIGINT NOT NULL,
  `role_id` BIGINT NOT NULL,
  CONSTRAINT `FK859n2jvi8ivhui0rl0esws6o`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommerceapp`.`user` (`user_id`),
  CONSTRAINT `FKa68196081fvovjhkek5m97n3y`
    FOREIGN KEY (`role_id`)
    REFERENCES `ecommerceapp`.`role` (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
